### ISSUE TITLE
npm start does not work following the READ.md instructions

### ISSUE THREAD

**Issue by saminkhan1** [contentful/gallery-app-react#6]
> cf-gallery-app-react@1.0.0 start C:\Users\samin\Documents\gallery-app
> NODE_ENV=development webpack-dev-server --host=0.0.0.0 --port=9020 --inline --hot

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cf-gallery-app-react@1.0.0 start: `NODE_ENV=development webpack-dev-server --host=0.0.0.0 --port=9020 --inline --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cf-gallery-app-react@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\samin\AppData\Roaming\npm-cache\_logs\2019-05-12T23_04_59_681Z-debug.log

Using a windows 10 system and node version v10.14.2
[2019-05-12T23_04_59_681Z-debug.log](https://github.com/contentful/gallery-app-react/files/3170660/2019-05-12T23_04_59_681Z-debug.log)
the attached file is the log file provided

**Comment by saminkhan1** [comment]
additional info: when i ran npm i the following came 

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN deprecated core-js@2.4.1: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> node-sass@3.13.1 install C:\Users\samin\Documents\gallery-app-react\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\Users\samin\Documents\gallery-app-react\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\samin\Documents\gallery-app-react\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\samin\\Documents\\gallery-app-react\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.14.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\samin\Documents\gallery-app-react\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\samin\Documents\gallery-app-react\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\samin\Documents\gallery-app-react\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\samin\Documents\gallery-app-react\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\samin\Documents\gallery-app-react\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\samin\Documents\gallery-app-react\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\samin\Documents\gallery-app-react\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\samin\Documents\gallery-app-react\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\samin\Documents\gallery-app-react\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\samin\Documents\gallery-app-react\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\samin\Documents\gallery-app-react\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\samin\Documents\gallery-app-react\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\Users\\samin\\Documents\\gallery-app-react\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\samin\\Documents\\gallery-app-react\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\samin\\Documents\\gallery-app-react\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\samin\\Documents\\gallery-app-react\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\samin\\Documents\\gallery-app-react\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\samin\\Documents\\gallery-app-react\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\samin\AppData\Local\Programs\Python\Python37-32\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\samin\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\samin\\Documents\\gallery-app-react\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\samin\Documents\gallery-app-react\node_modules\node-sass
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN babel-loader@6.4.1 requires a peer of babel-core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\samin\AppData\Roaming\npm-cache\_logs\2019-05-12T23_37_49_037Z-debug.log
